### ISSUE TITLE
Missing Tasks Git & Figma

### ISSUE THREAD

**Issue by syukronarie** [hariefairuzzaki/react_harie-fairuzzaki#4]
Bro @hariefairuzzaki 

Kmu buat PR aja yg task Git dan Figma

**Comment by hariefairuzzaki** [comment]
> Bro @hariefairuzzaki
> 
> Kmu buat PR aja yg task Git dan Figma

> untuk praktikum dan screenshot task 05_HTML yang hilang juga gimana mas?

**Comment by syukronarie** [comment]
> > Bro @hariefairuzzaki
> > Kmu buat PR aja yg task Git dan Figma
> 
> > untuk praktikum dan screenshot task 05_HTML yang hilang juga gimana mas?

Gak hilang, kamu trace aja di commit history, nanti ambil dan buat PR nya

**Comment by syukronarie** [comment]
Cari di commit di bawah ini,
<img width="1786" alt="Screen Shot 2022-08-27 at 1 13 24 PM" src="https://user-images.githubusercontent.com/36725290/187017680-fbec4c1c-0c27-41cd-b33b-9f944762e845.png">

**Comment by syukronarie** [comment]
Closed #5, #6
